apiVersion: apis.apps.tanzu.vmware.com/v1alpha1
kind: APIDescriptor
metadata:
  name: tanzu-app-deploy
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: tanzu-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-app-deploy
spec:
  type: openapi
  description: The Tanzu Simple API
  system: default/tanzu-app-system
  owner: default/default-team
  location:
    path: /v3/api-docs
    baseURL:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: tanzu-app-deploy

