apiVersion: awsblueprints.io/v1alpha1
kind: ServerlessApp
metadata:
  name: tanzu-app-deploy
spec:
  imageName: fmartin.azurecr.io/fmartin/tanzu-app-tap/tanzu-app-deploy-dev@sha256:796e18c38ae1764b62c50df0068f4d622c1de883bdc396647e7cb4aac27416de
  memorySize: 128
  resourceConfig:
    providerConfigName: aws-provider-config
    region: us-west-1

