apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- conditionMatchers:
  - type: ServiceAvailable
    status: "False"
    failure: true
  - type: ServiceAvailable
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: servicebinding.io/v1alpha3
      kind: ServiceBinding
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: tanzu-app-deploy-db
  annotations:
    autoscaling.knative.dev/minScale: "1"
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: tanzu-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-app-deploy
spec:
  name: db
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ClassClaim
    name: postgresql-claim
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: tanzu-app-deploy
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: tanzu-app-deploy-config
  annotations:
    autoscaling.knative.dev/minScale: "1"
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: tanzu-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-app-deploy
spec:
  name: config
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: sample-configuration-claim
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: tanzu-app-deploy

