apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tanzu-app-deploy
  labels:
    app.kubernetes.io/part-of: tanzu-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.name: tanzu-app
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-app-deploy
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: ""
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"tanzu-app","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web","tanzu.app.live.view":"true","tanzu.app.live.view.application.name":"tanzu-app"},"name":"tanzu-app-deploy","namespace":"default"},"spec":{"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/beeNotice/tanzu-app"}}}}
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-app
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: tanzu-app-deploy
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.name: tanzu-app
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
        image: harbor.withtanzu.com/fmartin/tanzu-app-tap/tanzu-app-deploy-default@sha256:65fd6ae45e6276e972c59c4d49c227b023a95333b218cf80b948c229d06df982
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

