apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tanzu-app-deploy
  labels:
    app.kubernetes.io/part-of: tanzu-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.name: tanzu-app
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-app-deploy
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        boot.spring.io/actuator: http://:8080/actuator
        boot.spring.io/version: 2.5.9
        conventions.apps.tanzu.vmware.com/applied-conventions: |-
          appliveview-sample/app-live-view-connector
          appliveview-sample/app-live-view-appflavours
          appliveview-sample/app-live-view-systemproperties
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          spring-boot-convention/spring-boot-actuator
          spring-boot-convention/service-intent-postgres
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{"autoscaling.knative.dev/minScale":"1","serviceclaims.supplychain.apps.x-tanzu.vmware.com/extensions":"{\"kind\":\"ServiceClaimsExtension\",\"apiVersion\":\"supplychain.apps.x-tanzu.vmware.com/v1alpha1\",\"spec\":{\"serviceClaims\":{\"db\":{\"namespace\":\"postgresql\"}}}}"},"labels":{"app.kubernetes.io/part-of":"tanzu-app","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web","tanzu.app.live.view":"true","tanzu.app.live.view.application.name":"tanzu-app"},"name":"tanzu-app-deploy","namespace":"dev"},"spec":{"env":[{"name":"SPRING_PROFILES_ACTIVE","value":"prod"}],"serviceClaims":[{"name":"db","ref":{"apiVersion":"sql.tanzu.vmware.com/v1","kind":"Postgres","name":"postgres-tanzu-app"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/beeNotice/tanzu-app"}}}}
        serviceclaims.supplychain.apps.x-tanzu.vmware.com/extensions: '{"kind":"ServiceClaimsExtension","apiVersion":"supplychain.apps.x-tanzu.vmware.com/v1alpha1","spec":{"serviceClaims":{"db":{"namespace":"postgresql"}}}}'
        services.conventions.apps.tanzu.vmware.com/postgres: postgresql/42.2.24
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-app
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: tanzu-app-deploy
        conventions.apps.tanzu.vmware.com/framework: spring-boot
        services.conventions.apps.tanzu.vmware.com/postgres: workload
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.flavours: spring-boot
        tanzu.app.live.view.application.name: tanzu-app
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: JAVA_TOOL_OPTIONS
          value: -Dmanagement.endpoint.health.show-details="always" -Dmanagement.endpoints.web.base-path="/actuator" -Dmanagement.endpoints.web.exposure.include="*" -Dmanagement.server.port="8080" -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: harbor.withtanzu.com/fmartin/tanzu-app-tap/tanzu-app-deploy-dev@sha256:4568f65f456f7ffc05a99cf5f64ef046f7c5db0fa054a8639b6b61d128cf5ab7
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

